package app.span.android;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import android.Manifest;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.os.Build;
import androidx.lifecycle.Lifecycle;
import androidx.test.core.app.ActivityScenario;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(AndroidJUnit4.class)
public final class PcToAndroidClipboardTest {
    // Generated by the Rust desktop implementation. This fixed vector proves
    // Rust X25519/HKDF/ChaCha20-Poly1305 packets remain Android-compatible.
    private static final String PC_ID = "rust-test-pc";
    private static final String PC_PUBLIC =
            "59716dbff7b07fe4ae16c18e7712a4a9d6036e9737f621f6f9e7144e9651241d";
    private static final String ANDROID_PRIVATE =
            "b34293c9e4883a86feb43c65fc1bfa806ab709e2465965727555301b5e0db991";
    private static final String ANDROID_PUBLIC =
            "bc8be9171b797e0f82222994e58411ab111db7832c2d0755f1208f4252d60066";
    private static final String NONCE = "fe73b77324bf874d744d4bc6";
    private static final String CIPHERTEXT =
            "3d5f060122a3ad13c0b30bd288e941ac9f2e4ebe0912c114459e098d00076719"
                    + "fc3060f3fd4b43b430dcaceb6d87b4b4";
    private static final String EXPECTED = "Rust PC to Android clipboard ✓";
    private static final String SECOND_EXPECTED = "Second PC clipboard update ✓";

    private Context context;

    @Before public void setUp() {
        context = InstrumentationRegistry.getInstrumentation().getTargetContext();
        context.getSharedPreferences("span", Context.MODE_PRIVATE).edit()
                .clear()
                .putString("identity.id", "android-test")
                .putString("identity.name", "Android Test")
                .putString("identity.private", ANDROID_PRIVATE)
                .putString("identity.public", ANDROID_PUBLIC)
                .commit();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            InstrumentationRegistry.getInstrumentation().getUiAutomation()
                    .grantRuntimePermission(
                            context.getPackageName(), Manifest.permission.POST_NOTIFICATIONS);
        }
        new SpanStore(context).saveDevices(Collections.singletonList(new SpanDevice(
                PC_ID,
                "Rust Test PC",
                "windows",
                "127.0.0.1",
                PC_PUBLIC,
                true,
                System.currentTimeMillis())));
    }

    @After public void tearDown() {
        SpanReceiveService.stop(context);
        context.getSharedPreferences("span", Context.MODE_PRIVATE).edit().clear().commit();
    }

    @Test public void repeatedRustPcPacketsUpdateAndroidSystemClipboardInBackground()
            throws Exception {
        SpanTextPacket rustPacket = SpanTextPacket.parse(fixedRustPacket().trim());
        assertEquals(
                "Rust packet must decrypt on Android before testing the service",
                EXPECTED,
                SpanCrypto.decryptText(rustPacket, ANDROID_PRIVATE, PC_PUBLIC));

        SpanDevice trusted = new SpanStore(context).trustedDevice(PC_ID);
        assertNotNull("test PC must be present in the service trust store", trusted);
        assertEquals(PC_PUBLIC, trusted.publicKeyHex);

        try (ActivityScenario<MainActivity> activity = ActivityScenario.launch(MainActivity.class)) {
            SpanReceiveService.start(context);

            // Put Span's UI in the background. Only its real foreground receiver
            // service remains active while both PC packets arrive.
            activity.moveToState(Lifecycle.State.CREATED);
            sendRawPacketWithRetry(fixedRustPacket());
            Thread.sleep(250);
            activity.moveToState(Lifecycle.State.RESUMED);
            assertClipboardEventuallyEquals(EXPECTED);

            activity.moveToState(Lifecycle.State.CREATED);
            // A fresh encrypted packet exercises the production receive path a
            // second time, guarding against the observed "first copy only" bug.
            SpanCrypto.Encrypted second = SpanCrypto.encryptText(
                    SECOND_EXPECTED, ANDROID_PRIVATE, PC_PUBLIC);
            sendRawPacketWithRetry(packetLine(second.nonceHex, second.ciphertextHex));
            Thread.sleep(250);
            activity.moveToState(Lifecycle.State.RESUMED);
            assertClipboardEventuallyEquals(SECOND_EXPECTED);
        }
    }

    private String fixedRustPacket() {
        return packetLine(NONCE, CIPHERTEXT);
    }

    private String packetLine(String nonce, String ciphertext) {
        return SpanProtocol.TEXT_MAGIC + "\t" + PC_ID + "\t" + nonce + "\t"
                + ciphertext + "\n";
    }

    private void sendRawPacketWithRetry(String line) throws Exception {
        byte[] data = line.getBytes(StandardCharsets.UTF_8);
        Exception last = null;
        long deadline = System.currentTimeMillis() + 5000;
        while (System.currentTimeMillis() < deadline) {
            try (Socket socket = new Socket()) {
                socket.connect(new InetSocketAddress("127.0.0.1", SpanProtocol.TEXT_PORT), 500);
                OutputStream output = socket.getOutputStream();
                output.write(data);
                output.flush();
                return;
            } catch (Exception error) {
                last = error;
                Thread.sleep(100);
            }
        }
        if (last != null) throw last;
        throw new AssertionError("receiver did not start");
    }

    private void assertClipboardEventuallyEquals(String expected) throws Exception {
        ClipboardManager clipboard =
                (ClipboardManager) context.getSystemService(Context.CLIPBOARD_SERVICE);
        assertNotNull(clipboard);
        long deadline = System.currentTimeMillis() + 5000;
        String actual = null;
        while (System.currentTimeMillis() < deadline) {
            ClipData clip = clipboard.getPrimaryClip();
            if (clip != null && clip.getItemCount() > 0) {
                CharSequence value = clip.getItemAt(0).coerceToText(context);
                actual = value == null ? null : value.toString();
                if (expected.equals(actual)) return;
            }
            Thread.sleep(100);
        }
        assertEquals(expected, actual);
    }
}
